# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: "2022 smdn <smdn@smdn.jp>"

# ref: https://docs.github.com/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  exclude:
    authors:
      - smdn
    labels:
      - release-target
