// Smdn.TPSmartHomeDevices.MacAddressEndPoint.dll (Smdn.TPSmartHomeDevices.MacAddressEndPoint-1.1.0)
//   Name: Smdn.TPSmartHomeDevices.MacAddressEndPoint
//   AssemblyVersion: 1.1.0.0
//   InformationalVersion: 1.1.0+26b3994b9e663ddd0b4c39b0a86948a876d03dad
//   TargetFramework: .NETStandard,Version=v2.1
//   Configuration: Release
//   Referenced assemblies:
//     Smdn.Net.AddressResolution, Version=1.0.0.0, Culture=neutral
//     Smdn.TPSmartHomeDevices.Primitives, Version=1.0.0.0, Culture=neutral
//     netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
#nullable enable annotations

using System;
using System.Net;
using System.Net.NetworkInformation;
using System.Threading;
using System.Threading.Tasks;
using Smdn.Net;
using Smdn.Net.AddressResolution;
using Smdn.TPSmartHomeDevices;

namespace Smdn.TPSmartHomeDevices {
  public class MacAddressDeviceEndPointFactory :
    IDeviceEndPointFactory<PhysicalAddress>,
    IDisposable
  {
    protected class MacAddressDeviceEndPoint : IDynamicDeviceEndPoint {
      public MacAddressDeviceEndPoint(IAddressResolver<PhysicalAddress, IPAddress> resolver, PhysicalAddress address) {}

      public void Invalidate() {}
      public async ValueTask<EndPoint?> ResolveAsync(CancellationToken cancellationToken) {}
      public override string ToString() {}
    }

    [Obsolete("Use an overload that specifies the parameter `shouldDisposeResolver`.")]
    protected MacAddressDeviceEndPointFactory(IAddressResolver<PhysicalAddress, IPAddress> resolver, IServiceProvider? serviceProvider = null) {}
    protected MacAddressDeviceEndPointFactory(IAddressResolver<PhysicalAddress, IPAddress> resolver, bool shouldDisposeResolver, IServiceProvider? serviceProvider) {}
    public MacAddressDeviceEndPointFactory(IPNetworkProfile networkProfile, IServiceProvider? serviceProvider = null) {}
    public MacAddressDeviceEndPointFactory(IPNetworkProfile networkProfile, TimeSpan networkScanInterval, TimeSpan networkScanMinInterval, IServiceProvider? serviceProvider = null) {}
    [Obsolete("Use an overload that specifies the parameter `shouldDisposeResolver`.")]
    public MacAddressDeviceEndPointFactory(MacAddressResolverBase resolver, IServiceProvider? serviceProvider = null) {}
    public MacAddressDeviceEndPointFactory(MacAddressResolverBase resolver, bool shouldDisposeResolver, IServiceProvider? serviceProvider = null) {}

    public virtual IDeviceEndPoint Create(PhysicalAddress address) {}
    protected virtual void Dispose(bool disposing) {}
    public void Dispose() {}
    protected void ThrowIfDisposed() {}
  }
}
// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.2.2.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.2.0.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
