// Smdn.TPSmartHomeDevices.MacAddressEndPoint.dll (Smdn.TPSmartHomeDevices.MacAddressEndPoint-1.2.0)
//   Name: Smdn.TPSmartHomeDevices.MacAddressEndPoint
//   AssemblyVersion: 1.2.0.0
//   InformationalVersion: 1.2.0+66f3966f8c2864562a16625b12052994056bc7d3
//   TargetFramework: .NETCoreApp,Version=v10.0
//   Configuration: Release
//   Metadata: IsTrimmable=True
//   Metadata: RepositoryUrl=https://github.com/smdn/Smdn.TPSmartHomeDevices
//   Metadata: RepositoryBranch=main
//   Metadata: RepositoryCommit=66f3966f8c2864562a16625b12052994056bc7d3
//   Referenced assemblies:
//     Smdn.Net.AddressResolution, Version=1.0.0.0, Culture=neutral
//     Smdn.TPSmartHomeDevices.Primitives, Version=1.1.1.0, Culture=neutral
//     System.ComponentModel, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Net.NetworkInformation, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Net.Primitives, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
#nullable enable annotations

using System;
using System.Net;
using System.Net.NetworkInformation;
using System.Threading;
using System.Threading.Tasks;
using Smdn.Net;
using Smdn.Net.AddressResolution;
using Smdn.TPSmartHomeDevices;

namespace Smdn.TPSmartHomeDevices {
  public class MacAddressDeviceEndPointFactory :
    IDeviceEndPointFactory<PhysicalAddress>,
    IDisposable
  {
    protected class MacAddressDeviceEndPoint : IDynamicDeviceEndPoint {
      public MacAddressDeviceEndPoint(IAddressResolver<PhysicalAddress, IPAddress> resolver, PhysicalAddress address) {}

      public void Invalidate() {}
      public async ValueTask<EndPoint?> ResolveAsync(CancellationToken cancellationToken) {}
      public override string ToString() {}
    }

    [Obsolete("Use an overload that specifies the parameter `shouldDisposeResolver`.")]
    protected MacAddressDeviceEndPointFactory(IAddressResolver<PhysicalAddress, IPAddress> resolver, IServiceProvider? serviceProvider = null) {}
    protected MacAddressDeviceEndPointFactory(IAddressResolver<PhysicalAddress, IPAddress> resolver, bool shouldDisposeResolver, IServiceProvider? serviceProvider) {}
    public MacAddressDeviceEndPointFactory(IPNetworkProfile networkProfile, IServiceProvider? serviceProvider = null) {}
    public MacAddressDeviceEndPointFactory(IPNetworkProfile networkProfile, TimeSpan networkScanInterval, TimeSpan networkScanMinInterval, IServiceProvider? serviceProvider = null) {}
    [Obsolete("Use an overload that specifies the parameter `shouldDisposeResolver`.")]
    public MacAddressDeviceEndPointFactory(MacAddressResolverBase resolver, IServiceProvider? serviceProvider = null) {}
    public MacAddressDeviceEndPointFactory(MacAddressResolverBase resolver, bool shouldDisposeResolver, IServiceProvider? serviceProvider = null) {}

    public virtual IDeviceEndPoint Create(PhysicalAddress address) {}
    protected virtual void Dispose(bool disposing) {}
    public void Dispose() {}
    protected void ThrowIfDisposed() {}
  }
}
// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.7.1.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.5.0.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
